### ISSUE TITLE
Huge gif image causes git and plugin managers to fail

### ISSUE THREAD

**Issue by rafi** [gelguy/snapshot.vim#1]
Commit cecd0da1 introduces a huge gif file, almost **1mb**, it causes a fresh new git clone to take ages and fail under certain internet connections. Please place animated gif in some external source, and completely remove `snapshot.gif` from Git history, you'll need to rewrite the tree:

``` sh
git filter-branch --tree-filter 'rm -f snapshot.gif' HEAD
git gc
git push --force
```

**Comment by gelguy** [comment]
Thanks for the report! The .gif is now removed. Will add it back to the readme in a later commit. 

This means later pulls will have to use

```
git fetch --all
git reset --hard origin/master
```

**Comment by rafi** [comment]
Thanks!
